$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
compute:  azureml:[compute instance]
display_name: r-accidents-example
experiment_name: r-accidents-example
description: Train a GLM using R on the accidents dataset.  
jobs:
  train:
    command:   Rscript accidents.R
                --data ${{inputs.training_data}}
                --out ${{outputs.model_out}}
    code:
      local_path: src
    environment:
      azureml:[environment]:[env_version]
    inputs:
      training_data:
        dataset: 
          local_path: data
        mode: ro_mount
    outputs:
      model_out:
        mode: upload
  eval:
    command:   Rscript eval_model.r
                --model ${{inputs.model}}
    code:
      local_path: src
    environment:
      azureml:[environment]:[env_version]
    inputs:
      model: ${{jobs.train.outputs.model_out}}