---
title: "R Notebook"
output: html_notebook
---

```{r}
library(reticulate)
library(tidyverse)
```

```{r}
# Tell reticulate which conda AzureML env to use if on local desktop.
# If on a CI, this is unnecessary
#use_condaenv("AzureML")

# Import azureml.core python package
azureml <- import("azureml.core")
```

```{r}

cli_auth = azureml$authentication$AzureCliAuthentication()

# Get reference to AzureML workspace if on CI (via RStudio). No auth needed
#ws <- azureml$Workspace$from_config()

# Get reference to AzureML workspace if on local desktop. This will
# prompt a broswer for interactive authentication
ws <- azureml$Workspace$get(name="wu2modtimesmlsw",
                            subscription_id="7fd76d0f-84f2-498b-a997-e0d059af5ce1",
                            resource_group='wu2modtimerg',
                            auth=cli_auth)
```

```{r}
# Tabular dataset example. Read pandas DF directly to R DF
tab_dataset <- azureml$Dataset$get_by_name(ws, name="scored_auto_data")
data_df1 <- tab_dataset$to_pandas_dataframe()
head(data_df1)
```
```{r}
data_df1['new'] <- 1
datastore = ws$get_default_datastore()
dataset = azureml$Dataset$Tabular$register_pandas_dataframe(data_df1, datastore, "scored_auto_data_from_r", show_progress=TRUE)

```

```{r}
# File dataset example. Downloads file data set to local directory then reads CSV.
file_dataset <- azureml$Dataset$get_by_name(ws, name="auto_score_file")
data_file <- file_dataset$download(target_path='./data', overwrite=TRUE)
data_df2 <- read.csv(data_file)
head(data_df2)
```


```{r}
registered_ds = file_dataset$register(workspace=ws,
                                 name='auto_score_file_from_r',
                                 description=' training data',
                                 create_new_version=TRUE)
```

